// Types
export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';
export const POST_MESSAGE_SUCCESS = 'POST_MESSAGE_SUCCESS';
export const POST_MESSAGE_LOADING = 'POST_MESSAGE_LOADING';
export const POST_MESSAGE_ERROR = 'POST_MESSAGE_ERROR';

