/*
Reverse an string for bot answer
*/
export function reverse(str) {
  return str.split('').reverse().join('');
}

/* 
Validates an email with a regular expression 
from : https://stackoverflow.com/questions/46155/validate-email-address-in-javascript
*/

/* Next line disables eslint warning generated by regex */
/*eslint no-useless-escape: "off"*/

export function validateEmail(email) {
    var re = /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
    return re.test(email);
}
